title: Just The Dawgs
description: Collaborative Assignment
theme: just-the-docs

url: https://Sapin5.github.io/Just-The-Docs-Template

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/Sapin5/Just-The-Docs-Template
